import { describe, expect, it } from "vitest";
import { acceptGenerationProviderResponse, assertNewProviderJobId, beginGenerationFinalizationRetry, beginGenerationProviderRetry, GENERATION_DISPOSITION_TRANSITIONS, isGenerationPollingActive, isGenerationTerminal, shouldResumeGenerationAfterReload, transitionGenerationDisposition, type GenerationJob, type GenerationDisposition, type GenerationRouteIdentity } from "./contracts.js";

export const route: GenerationRouteIdentity = { providerInstanceId: "instance-1", providerModelId: "model-1", requestedMode: "text-to-video", providerSchemaId: "schema-1", providerEndpointId: "endpoint-1", providerSchemaVersion: "v1" };
export function makeJob(status: GenerationDisposition): GenerationJob { const attempt = { attemptNumber: 1, routing: route, providerJobId: "provider-1", startedAt: 1000 }; return { schemaVersion: 2, contractVersion: 2, id: "job-1", projectId: "project-1", provider: "wavespeed", providerInstanceId: route.providerInstanceId, modelId: "model-1", modelSchemaVersion: "v1", routing: route, providerJobId: attempt.providerJobId, status, attempt: 1, context: { projectId: "project-1", entryContext: { kind: "new-asset" }, mode: "text-to-video", placementPolicy: "none", prompt: "a test", references: [] }, providerInputs: { seed: 0, enhance: false }, attempts: [attempt], checkpoints: {}, createdAt: 1000, updatedAt: 1000 }; }

describe("generation-job-dispositions.fixture", () => {
  it("accepts every listed transition", () => { for (const [from, next] of Object.entries(GENERATION_DISPOSITION_TRANSITIONS) as [GenerationDisposition, readonly GenerationDisposition[]][]) for (const to of next) expect(transitionGenerationDisposition(makeJob(from), to).status).toBe(to); });
  it("rejects every unlisted transition without mutation", () => { for (const from of Object.keys(GENERATION_DISPOSITION_TRANSITIONS) as GenerationDisposition[]) for (const to of Object.keys(GENERATION_DISPOSITION_TRANSITIONS) as GenerationDisposition[]) if (!GENERATION_DISPOSITION_TRANSITIONS[from].includes(to)) { const job = makeJob(from); expect(() => transitionGenerationDisposition(job, to)).toThrow("generation-invalid-transition"); expect(job.status).toBe(from); } });
  it("matches polling and terminality rules", () => { expect(isGenerationPollingActive("queued")).toBe(true); expect(isGenerationPollingActive("submitting")).toBe(true); expect(isGenerationPollingActive("running")).toBe(true); expect(isGenerationPollingActive("finalizing")).toBe(true); expect(isGenerationPollingActive("needs-attention")).toBe(false); for (const status of ["canceled", "failed", "succeeded"] as const) expect(isGenerationTerminal(status)).toBe(true); expect(isGenerationTerminal("needs-attention")).toBe(false); });
  it("rejects a canceled late response through the ownership predicate", () => { const canceled = transitionGenerationDisposition(makeJob("queued"), "canceled"); expect(acceptGenerationProviderResponse(canceled, "project-1", 1, "provider-1")).toBe(false); });
  it("resumes only the reload dispositions with durable ownership", () => { for (const status of ["queued", "submitting", "running", "finalizing"] as const) expect(shouldResumeGenerationAfterReload(makeJob(status))).toBe(true); for (const status of ["needs-attention", "failed", "canceled", "succeeded", "completed"] as const) expect(shouldResumeGenerationAfterReload(makeJob(status))).toBe(false); expect(shouldResumeGenerationAfterReload({ ...makeJob("running"), providerJobId: undefined, attempts: [{ ...makeJob("running").attempts[0], providerJobId: undefined }] })).toBe(false); });
  it("increments logical attempt and provider ID exactly once on provider retry", () => { let providerSubmitCount = 0; const submitRetry = (job: GenerationJob, providerJobId: string) => { providerSubmitCount += 1; return beginGenerationProviderRetry(job, providerJobId, 2000); }; const retried = submitRetry(makeJob("failed"), "provider-2"); expect(providerSubmitCount).toBe(1); expect(retried.status).toBe("submitting"); expect(retried.attempt).toBe(2); expect(retried.providerJobId).toBe("provider-2"); expect(retried.attempts.map((attempt) => attempt.providerJobId)).toEqual(["provider-1", "provider-2"]); expect(() => assertNewProviderJobId("provider-1", "provider-1")).toThrow("generation-provider-job-id-reused"); });
  it("retries finalization without another provider submission", () => { let providerSubmitCount = 0; const completed = { ...makeJob("needs-attention"), output: { mediaId: "media-1", versionId: "version-1", mimeType: "video/mp4", byteLength: 0, sha256: "sha-1" } }; const recovered = beginGenerationFinalizationRetry(completed); expect(recovered.status).toBe("finalizing"); expect(providerSubmitCount).toBe(0); const succeeded = transitionGenerationDisposition(recovered, "succeeded"); expect(succeeded.attempts).toHaveLength(1); expect(providerSubmitCount).toBe(0); });
});
